const { chromium } = require('playwright'); const fs = require('fs');
const SC = '/tmp/claude-0/-home-claude/dd9ce749-5a99-545b-9acc-0332c785cc1e/scratchpad/'; const O=SC+'uxa/';
const route = async route=>{const u=route.request().url();const map={'deck.gl@9.4.0/dist.min.js':'deck.js','pako_inflate.min.js':'pako.js','jspdf.umd.min.js':'jspdf.js','xlsx.full.min.js':'xlsx.js'};for(const k in map) if(u.includes(k)){const p=SC+'libs/'+map[k];if(fs.existsSync(p))return route.fulfill({path:p,contentType:'application/javascript'});} if(u.startsWith('https://fonts.'))return route.fulfill({status:200,body:'',contentType:'text/css'}); return route.continue();};
(async () => {
  const proxy = process.env.HTTPS_PROXY;
  const browser = await chromium.launch({proxy:proxy?{server:proxy}:undefined,args:['--ignore-certificate-errors','--use-gl=swiftshader','--enable-unsafe-swiftshader']});
  const page = await (await browser.newContext({viewport:{width:1440,height:900}})).newPage(); page.setDefaultTimeout(150000);
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*', route);
  await page.goto('file://'+SC+'variant.html'); await page.waitForSelector('#loader[hidden]',{state:'attached'}); await page.waitForTimeout(3500);
  await page.screenshot({path:O+'v_ciudad.png', timeout:150000}); console.log('v_ciudad');
  const ix = await page.$eval('#alc', e=>[...e.options].findIndex(o=>o.text.includes('Iztapalapa')));
  await page.selectOption('#alc',{index:ix}); await page.waitForTimeout(6000);
  await page.screenshot({path:O+'v_iztapalapa.png', timeout:150000}); console.log('v_iztapalapa');
  await page.fill('#col-q','Roma Norte'); await page.waitForTimeout(1800);
  const li=await page.$$('#col-list li[role=option]'); console.log('sug', li.length? await li[0].innerText():'none'); if(li.length) await li[0].click({noWaitAfter:true});
  await page.waitForTimeout(5000); await page.click('#card .close',{noWaitAfter:true}).catch(()=>{});
  await page.click('#zin',{noWaitAfter:true}); await page.waitForTimeout(4000);
  await page.screenshot({path:O+'v_colonia_etiquetas.png', timeout:150000}); console.log('v_colonia');
  console.log('errors', errors.join('\n')||'none');
  await browser.close();
})().catch(e=>{console.error('FAILED',e.message);process.exit(1)});
